const HANDLE_MODAL = 'HANDLE_MODAL'
const SET_MESSAGE = 'SET_MESSAGE'
const LOADING_APP = 'LOADING_APP'
const LOGOUT = 'LOGOUT'
const CURRENT = 'CURRENT'

const CREATE_CONFIGURACION = 'CREATE_CONFIGURACION'
const CREATE_ARTICULO = 'CREATE_ARTICULO'
const CREATE_TIPOARTICULO = 'CREATE_TIPOARTICULO'
const AGREGAR_MARCAS = 'AGREGAR_MARCAS'

const GET_CONFIGURATION = 'GET_CONFIGURATION'
const TRAER_TIPOARTICULO = 'TRAER_TIPOARTICULO'
const GET_ARTICLES = 'GET_ARTICLES'
const TRAER_MARCAS = 'TRAER_MARCAS'
const GET_OFFERS = 'GET_OFFERS'

const SACAR_CARRITO = 'SACAR_CARRITO'
const AGREGAR_COMPROBANTES = 'AGREGAR_COMPROBANTES'

const ADDARTICLEVIEW = 'ADDARTICLEVIEW'

const GET_BOXES = 'GET_BOXES'

const SUCCESSFUL_PURCHASE = 'SUCCESSFUL_PURCHASE'
const AGREGAR_DETALLE_COMPROBANTE = 'AGREGAR_DETALLE_COMPROBANTE'

export default {
    HANDLE_MODAL,
    LOADING_APP,
    SET_MESSAGE,
    LOGOUT,
    CURRENT,

    CREATE_CONFIGURACION,
    GET_CONFIGURATION,

    CREATE_TIPOARTICULO,
    TRAER_TIPOARTICULO,

    GET_ARTICLES,
    CREATE_ARTICULO,
    SACAR_CARRITO,
    AGREGAR_COMPROBANTES,
    AGREGAR_DETALLE_COMPROBANTE,
    AGREGAR_MARCAS,
    TRAER_MARCAS,

    ADDARTICLEVIEW,
    GET_OFFERS,
    GET_BOXES,
    SUCCESSFUL_PURCHASE,
}
