export enum AppConstant {
    LOGIN = '[User] LOGIN',
    LOGGED_USER = '[User] LOGGED_USER',
    ERROR = '[User] ERROR',
    LOGOUT = '[User] LOGOUT',
    GET_AUTHENTICATED_CLIENT = '[User] GET_AUTHENTICATED_CLIENT',
    AUTHENTICATED_CLIENT = '[User] AUTHENTICATED_CLIENT',
    ADD_ITEM_CART = '[Cart] ADD_ITEM',
    REMOVE_ONE_ITEM_CART = '[Cart] REMOVE_ONE_ITEM',
    REMOVE_ALL_ITEMS_CART = '[Cart] REMOVE_ALL_ITEMS',
    CHANGE_PROFILE = '[Client] CHANGE_PROFILE'
}