const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
const LOGIN_ERROR = 'LOGIN_ERROR'
const SIGNUP_SUCCEEDED = 'SIGNUP_SUCCEEDED'
const SIGNUP_ERROR = 'SIGNUP_ERROR'
const CLOSE_SESION = 'CLOSE_SESION'
const GET_USER = 'GET_USER'
const ADD_ARTICLE_TO_TROLLEY = 'ADD_ARTICLE_TO_TROLLEY'
const DELETE_ARTICLE_TO_TROLLEY = 'DELETE_ARTICLE_TO_TROLLEY'
const SUCCESSFULL_PURCHASE_CLIENT = 'SUCCESSFULL_PURCHASE_CLIENT'

export default {
    LOGIN_SUCCEEDED,
    LOGIN_ERROR,
    SIGNUP_SUCCEEDED,
    SIGNUP_ERROR,
    CLOSE_SESION,
    GET_USER,

    ADD_ARTICLE_TO_TROLLEY,
    SUCCESSFULL_PURCHASE_CLIENT,
    DELETE_ARTICLE_TO_TROLLEY
}
